name: Deploy a PRUEBAS
on:
  push: { branches: [develop] }
jobs:
  deploy:
    uses: mazeos/maze-infra/.github/workflows/deploy.yml@main
    with: { app_dir: /opt/web-oficial-dev, branch: develop, compose_file: docker-compose.dev.yml }
    secrets: inherit
